
class Type:
    SOLID = 1
    NONREACTIVE_SOLID = 2
    INTERFACE = -2
    LIQUID = -1
    MULTILEVEL = -5
    MULTILEVEL_CH = -6
	
    #FULL_MULTILEVEL = -6
    #FULLY_DISSOLVED = -9
    #FULLY_PRECIPITATED = -10

